### ISSUE TITLE
IOError: Error while reading from plink file.

### ISSUE THREAD

**Issue by ruthjohnson95** [yiminghu/PleioPred#2]
Hi,

I've been trying to run PleioPred, but I can't seem to run it successfully on the non-testing data. I found that when my .bim file is >10,000 lines, I get the error below or a memory error. I'm using a cluster and was doing computations on a 30G node, so I am not sure why memory seems to be a problem. 

Best,
Ruthie 

```
Iterating over file to load SNPs
Traceback (most recent call last):
  File "/u/home/r/ruthjohn/ruthjohn/PleioPred/PleioPred.py", line 285, in <module>
    main(process_args(args))
  File "/u/home/r/ruthjohn/ruthjohn/PleioPred/PleioPred.py", line 243, in main
    coord_trimmed.main(pdict_coord_trimmed(pdict, '1'))
  File "/u/project/pasaniuc/pasaniucdata/ruthjohn/PleioPred/pleiopred/coord_trimmed.py", line 1032, in main
    hdf5_file=h5f, min_maf=p_dict['maf'])
  File "/u/project/pasaniuc/pasaniucdata/ruthjohn/PleioPred/pleiopred/coord_trimmed.py", line 856, in coordinate_genotypes_ss_w_ld_ref
    raw_snps,freqs = _parse_plink_snps_(genotype_file, snp_indices)
  File "/u/project/pasaniuc/pasaniucdata/ruthjohn/PleioPred/pleiopred/coord_trimmed.py", line 58, in _parse_plink_snps_
    plinkf.next()
  File "/u/home/r/ruthjohn/.local/lib/python2.7/site-packages/plinkio/plinkfile.py", line 58, in next
    row = cplinkio.next_row( self.handle )
IOError: Error while reading from plink file.
```

**Comment by yiminghu** [comment]
Hi Ruth,

The error was raised by plinkio module. So I think there might be something wrong with the plink files. Could you double check if the plink files are in correct form or you could share a screen-shot of .bim file if you don’t mind? Thanks!

Best regards,

Yiming
-- 

Yiming Hu

Yale School of Public Health | May 2018
Biostatistics Ph.D Candidate
yiming.hu@yale.edu <mailto:yiming.hu@yale.edu> | 203-988-3490

**Comment by ruthjohnson95** [comment]
Hi Yiming,

Thanks for the quick reply! 

Here's the head of the .bim file I'm using:

```
1	rs535605744	0	1043557	T	C
1	rs555684725	0	1043590	A	G
1	rs566020904	0	1043621	T	C
1	rs533574128	0	1043640	A	G
1	rs553704858	0	1043648	G	A
1	rs576737249	0	1043676	T	C
1	rs76099452	0	1043737	C	T
1	rs12751333	0	1043743	C	T
1	rs548829137	0	1043746	T	TCAC
1	rs576307341	0	1043804	T	C
```
The entire file is ~6 million lines. Since I thought it was a memory issue at first, I just used the first 10,000 lines to test it, which seemed to work. It was when I used any file larger than that where I get the error.

**Comment by yiminghu** [comment]
I see. The largest file I have ever ran with plinkio is no larger than one million SNPs so I am not sure if they could handle such a large file. Have you tried using only the genotyped SNP (should be around 500,000 SNPs)?

Best regards,

Yiming
-- 

Yiming Hu

Yale School of Public Health | May 2018
Biostatistics Ph.D Candidate
yiming.hu@yale.edu <mailto:yiming.hu@yale.edu> | 203-988-3490

**Comment by ruthjohnson95** [comment]
Oh I see, so you're saying you've not yet used a .bim file that large before. 

And sorry, could you clarify what you mean by only using the genotyped SNPs? Do you mean as in, the bim file only containing the SNPs in the GWAS sum stats you're inputting?

**Comment by yiminghu** [comment]
Yes, I mean I have never used that many SNPs in this step. I was suggesting using a subset of SNPs to do risk prediction for example you could find a list of SNPs (those non-imputed, since based on the size, it seems the file you have contains inputed SNPs). Then use plink to extract the subset and get a smaller plink file.

Best,

Yiming
-- 

Yiming Hu

Yale School of Public Health | May 2018
Biostatistics Ph.D Candidate
yiming.hu@yale.edu <mailto:yiming.hu@yale.edu> | 203-988-3490

**Comment by ruthjohnson95** [comment]
Yes, that worked perfectly! Thank you again for your help.
