### ISSUE TITLE
cannot serialize a string larger than 2 GiB

### ISSUE THREAD

**Issue by cz354** [yiminghu/PleioPred#6]
When I run the code, there appears this problem:

Traceback (most recent call last):
  File "PleioPred.py", line 285, in <module>
    main(process_args(args))
  File "PleioPred.py", line 277, in main
    pleiopred_main.main(pdict_pred_partial(pdict, 'anno'))
  File "/gpfs/loomis/home.grace/cz354/ADGC/PleioPred/pleiopred/pleiopred_main.py", line 539, in main
    cPickle.dump(ld_dict, f, protocol=2)
OverflowError: cannot serialize a string larger than 2 GiB

When I search for the solution, it said python3 pickle.dump can use protocol=4. But the python version I use is 2.7. So I'd like to know how to solve this?

**Comment by yiminghu** [comment]
hi, there does not seem to be any good solution other than switching version. how many snps do you have in testing data? If it contains too many SNPs (> 1M per chromosome), might need to further 1) cut each chromosome into chunks; 2) run PleioPred on them separately; 3) sum the PRS computed from each chunks together.

we have plans to update the software to py3 but probably wont happen soon.

**Comment by cz354** [comment]
Hi
I have about 100,000 - 600,000 SNPs for each chromosome. I will try your
method. Thank you very much.
